In [2]:
import pandas as pd

df = pd.read_csv('./data/orders.csv')

In [ ]:
# Series (column)
values = [10, 20, 30 ,40 ,50]
s = pd.Series(values, index=['a', 'b', 'c', 'd', 'e'])

s.loc['a']

np.int64(10)

In [11]:
# Data Frame
df = pd.DataFrame({
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 22, 34, 30],
    'Job': ['Engineer', 'Doctor', 'Teacher', 'Lawyer']

})
df = df.set_index('Name')

In [12]:
df

       Age       Job
Name
John    28  Engineer
Anna    22    Doctor
Peter   34   Teacher
Linda   30    Lawyer

In [20]:
df1 = pd.DataFrame({
    'a': [1, 2, 3],
}, index=[0,1,2])
df2 = pd.DataFrame({
    'a': [10, 20, 30]
}, index=[1,2,0])

In [23]:
df1 + df2

    a
0  31
1  12
2  23

In [32]:
df.reset_index()

    Name  Age       Job
0   John   28  Engineer
1   Anna   22    Doctor
2  Peter   34   Teacher
3  Linda   30    Lawyer

In [34]:
df.to_csv('./data/df.csv')

In [31]:
pd.read_csv('./data/df.csv', index_col=0)

       Age       Job
Name
John    28  Engineer
Anna    22    Doctor
Peter   34   Teacher
Linda   30    Lawyer

In [35]:
df.to_json('./data/df.json')